### ISSUE TITLE
Any opportunities to add more loci to the analysis?

### ISSUE THREAD

**Issue by LiliiaY** [broadinstitute/str-analysis#7]
According to call_non_ref_pathogenic_motifs description, script can consider and generate calls  for 9 STR loci (RFC1, BEAN1, DAB1, MARCHF6, RAPGEF2, SAMD12, STARD7, TNRC6A, YEATS2). I am wondering is there a way to analyze another set of loci, for example, any other of the 59 loci listed here: https://github.com/broadinstitute/str-analysis/tree/main/str_analysis/variant_catalogs?

Thanks in advance!

**Comment by bw2** [comment]
Hi @LiliiaY , it's possible to add more loci to https://github.com/broadinstitute/str-analysis/blob/main/str_analysis/data/non_ref_motif.locus_info.json 
but I'm not aware of any other loci besides those 9 where there are known non-ref motifs. For the other loci in https://github.com/broadinstitute/str-analysis/tree/main/str_analysis/variant_catalogs , is there a reason you would prefer to use this script rather than running ExpansionHunter (or other tools) directly?
